// src/app/layout.tsx
import type { Metadata } from "next";
import "./globals.css";
import { Providers } from "./providers";
import TabBar from "@/components/tab-bar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko" className="h-full">
      <body
        className="
          h-full bg-black/5 text-gray-900 antialiased
          selection:bg-blue-100 selection:text-blue-900
        "
        style={{
          paddingLeft: "env(safe-area-inset-left)",
          paddingRight: "env(safe-area-inset-right)",
        }}
      >
        <div className="mx-auto min-h-screen max-w-[420px] bg-white shadow-sm">
          <Providers>{children}</Providers>
          <TabBar />
        </div>
      </body>
    </html>
  );
}
